<?php
$MESS["DISK_HELP_1"] = "<strong>Ở lưu trữ</strong> là nơi lưu trữ tập không giới hạn tập tin và giải pháp chia sẻ là khả dụng trong tài khoản Bitrix24 của bạn để sắp xếp các hoạt động trên tài liệu trong công ty bạn";
$MESS["DISK_HELP_2"] = "Quản lý Tập tin và Thư mục";
$MESS["DISK_HELP_3"] = "Tạo một Tài liệu mới";
$MESS["DISK_HELP_4"] = "Ổ lưu trữ Bitrix24 là gì";
$MESS["DISK_HELP_5"] = "Chia sẻ Tài liệu";
$MESS["DISK_HELP_6"] = "Theo dõi việc sử dụng Tài liệu";
$MESS["DISK_HELP_7"] = "Quản lý Tập tin và Thư mục";
$MESS["DISK_HELP_8"] = "Tính năng Ổ lưu trữ là cách đơn giản để duyệt các tập tin và thư mục và làm việc với chúng. Bạn có hai lựa chọn cho việc xem hay định tuyến đến chúng. Thứ nhất, một cách xem với dạng bảng rất thân thiện với các tập tin một cách có cấu trúc. Hai là bạn có thể xem tất cả các tập tin và thư mục trên cùng một trang mà thôi. Bạn có thể chọn một trong hai cách bằng một cú nhấn chuột để chuyển đổi giữa hai cách này.";
$MESS["DISK_HELP_9"] = "Tạo một Tài liệu mới";
$MESS["DISK_HELP_10"] = "Có vài cách để tạo tài liệu mới vào ổ lưu trữ của bạn. Thứ nhất, bạn đơn giản chỉ chọn vào nút Tải lên. Bạn cũng có thể kéo thả các tập tin từ máy tính. Để tạo một tài liệu mới từ chính bên trong tài khoản Bitrix24 của bạn, chọn \"Tài liệu mới\" và chọn \"Tạo sử dụng\", chọn Google Docs, MS Office Web App hay bất kỳ ứng dụng văn phòng nào có trên máy tính của bạn (chẳng hạn như Microsoft Office, Mac Pages, Open Office,.. v..v)";
$MESS["DISK_HELP_11"] = "Ổ lưu trữ Bitrix24 là gì?";
$MESS["DISK_HELP_12"] = "Bitrix24.Drive là một tập tin lưu trữ, đồng bộ, chỉnh sửa và chia sẻ hệ thống hoàn chỉnh. Cùng với các ứng dụng máy tính để bàn, Bitrix24.Drive cho phép bạn lưu trữ các tập tin cả trong các đám mây và các địa phương. Nếu bạn chỉnh sửa một tài liệu trên máy tính hoặc thiết bị của bạn, các bản sao lưu trữ trong đám mây được tự động đồng bộ hóa để phù hợp với phiên bản mới. Nó hoạt động giống như ma thuật - Bitrix24.Drive giúp bạn tiết kiệm những rắc rối của việc tải về và tải lên tập tin. Mở một tập tin, chỉnh sửa và gần gũi - cũng giống như bạn sẽ làm gì khi chỉnh sửa một tập tin trên máy tính của bạn. Phiên bản mới nhất của tài liệu sẽ có sẵn cho bạn và đồng nghiệp của bạn trong các đám mây cũng như trên máy tính của họ và các thiết bị di động. Đơn giản chỉ cần tải về các ứng dụng máy tính để bàn Bitrix24 và kết nối Bitrix24.Drive của bạn để có được quyền truy cập vào tính năng AutoSync đa thiết bị.";
$MESS["DISK_HELP_13"] = "chia sẻ Tài liệu";
$MESS["DISK_HELP_14"] = "Bạn có thể sử dụng Luồng bản tin chia sẻ tài liệu và thảo luận cùng một lúc. Bắt đầu bằng cách gõ một tin nhắn và gắn một tập tin từ Drive. Khi hoàn tất, nhấn \"Gửi\". các đồng nghiệp của bạn bây giờ có thể xem hoặc chỉnh sửa các tài liệu mà bạn đính kèm, nếu bạn cho phép. Mỗi lần có người tiết kiệm một phiên bản mới của tập tin, bình luận thông báo được thêm vào thông báo ban đầu của bạn, và các tập tin đính kèm được cập nhật. Lịch sử sửa đổi tập tin được lưu giữ, và người dùng có thể xem tất cả các phiên bản trước đó làm cho các tập tin và trở lại với một phiên bản cũ hơn, nếu cần thiết.";
$MESS["DISK_HELP_17"] = "Theo dõi tài liệu Sử dụng";
$MESS["DISK_HELP_18"] = "Tài liệu bên trong Bitrix24 có thể được sử dụng trong bất kỳ tổ chức cho phép đính kèm tập tin (Luồng bản tin, công việc, sự kiện Lịch, CRM). Bạn có thể xem các thực thể mà tập tin được sử dụng và những người dùng có quyền truy cập đến nó trong các thuộc tính tài liệu (File> Open). Chú ý rằng khi bạn xóa một tập tin từ ổ đĩa của bạn, bạn xóa nó từ tất cả các thực Bitrix24 nó được gắn vào là tốt.";
$MESS["DISK_HELP_19"] = "Điểm mấu chốt ở đây là - khi nói đến làm việc với các tài liệu, <strong>Bitrix24.Drive</strong> là người bạn tốt nhất của bạn mà bạn luôn luôn có thể dựa vào. Tìm hiểu thêm về Drive trong quá trình đào tạo.";
